server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_USER}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 32
