server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: test
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 32
  liquibase:
    change-log: classpath:db/changelog/db-changelog.yaml
